name: Pull Request Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        xcode-version: [15.4, 16.1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select ${{ matrix.xcode-version }}
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Build for iOS Simulator
        run: xcodebuild build -scheme ETDistribution -sdk iphonesimulator -destination 'generic/platform=iOS Simulator'
      - name: Build for iOS
        run: xcodebuild build -scheme ETDistribution -sdk iphoneos -destination 'generic/platform=iOS'
      - name: Build TestApp
        run: cd Example && xcodebuild build -scheme DemoApp -sdk iphonesimulator -destination 'generic/platform=iOS Simulator' -project DemoApp.xcodeproj