name: Build XCFramework

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        xcode-version: [15.4, 16.1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select ${{ matrix.xcode-version }}
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Build xcframework
        run: sh build.sh