name: Build XCFramework

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select
        run: sudo xcode-select -s '/Applications/Xcode_15.4.app/Contents/Developer'
      - name: Build xcframework
        run: sh build.sh