name: Release workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select
        run: sudo xcode-select -s '/Applications/Xcode_15.4.app/Contents/Developer'
      - name: Build xcframework
        run: sh build.sh
      - name: Zip xcframework
        run: zip -r ETDistribution.xcframework.zip ETDistribution.xcframework
      - name: Upload Artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ETDistribution.xcframework.zip
          body:
            Release ${{ github.ref }}
            Automated release created by GitHub Actions.