name: Pull Request Build

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-14
    strategy:
      matrix:
        xcode-version: [15.4, 16.1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select ${{ matrix.xcode-version }}
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Run tests
        run: xcodebuild -scheme 'ETDistribution' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro' test