name: Pull Request Build

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select
        run: sudo xcode-select -s '/Applications/Xcode_16.1.app/Contents/Developer'
      - name: Run tests
        run: xcodebuild -scheme 'ETDistribution' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Pro' test